# Generated by Django 2.0.6 on 2019-04-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerinfo',
            fields=[
                ('name', models.CharField(default='', max_length=225)),
                ('email', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=225)),
                ('gender', models.CharField(default='', max_length=225)),
                ('isactive', models.BooleanField(default=True)),
                ('dob', models.CharField(default='', max_length=225)),
                ('image', models.CharField(default='', max_length=255)),
                ('isavailable', models.BooleanField(default=True)),
                ('isqueue', models.BooleanField(default=True)),
                ('role_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager_app.UserRole')),
            ],
        ),
    ]
